version: "3.8"

services:
  execution:
    image: ethpandaops/erigon:2.53.0
    user: "root"
    command:
      --log.console.verbosity=3
      --datadir=/execution-data
      --port=50503
      --networkid=28256
      --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin,ots
      --http.vhosts=*
      --ws
      --allow-insecure-unlock
      --nat=extip:${IP_ADDRESS}
      --http
      --http.addr=0.0.0.0
      --http.corsdomain=*
      --http.port=8545
      --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=9001
      --bootnodes=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
      --staticpeers=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11245:8545" 
      - "11246:8546" 
      - "11251:8551" 
      - "12301:9001" 
      - "51603:50503"
    restart: unless-stopped

  beacon:
    image: sigp/lighthouse:v4.5.0
    user: "root"
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=11100
      - --enr-tcp-port=11100
      - --listen-address=0.0.0.0
      - --port=11100
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --import-all-attestations
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --trusted-peers=16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
      - --boot-nodes=enr:-MS4QKjvQWjHjNSlrgJBnwI7j88ULp36kH6FegWreBuiHL0_UGs4EvAxALKLgvKjTFpk6x0zTPyxoXXt0PDeZxlAihgBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjvkwgQAAAOP__________gmlkgnY0gmlwhFhjXm2EcXVpY4Iq-YlzZWNwMjU2azGhAoNhfDA57peBhfKlgRRDYKmjwOUPSPqj97hpWmwycgJdiHN5bmNuZXRzAIN0Y3CCKviDdWRwgir4
      - --checkpoint-sync-url=http://88.99.94.109:9781
      - --disable-optimistic-finalized-sync
      - --disable-backfill-rate-limiting
      - --genesis-backfill
      - --reconstruct-historic-states
      - --reset-payload-statuses
      - --disable-peer-scoring
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "12300:11100/udp"
      - "12300:11100/tcp" 
      - "4900:4000"
      - "8154:5054"
    depends_on:
      - execution
    restart: unless-stopped

  validator:
    image: sigp/lighthouse:v4.5.0
    user: "root"
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --validators-dir=/validator_keys/
      - --secrets-dir=/validator_keys/secrets
      - --init-slashing-protection
      - --http
      - --unencrypted-http-transport
      - --http-address=0.0.0.0
      - --http-port=5042
      - --beacon-nodes=http://beacon:4000
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5064
    volumes:
      - ./el-cl-genesis-data:/el-cl-genesis-data
      - ./validator_keys:/validator_keys
    ports:
      - "8142:5042"
      - "8164:5064"
    depends_on:
      - beacon
    restart: unless-stopped
